 
    <form action="confirm_main.php" method="post" enctype="multipart/form-data">
    <p>
	 <center>Please keep the volumeknob pushed in, and click the 'Run Upgrade' to update the Mainboard.</center>

	 <table>
		<tr>
			<h1> </h1> 
		</tr>
	    <tr>
	  	<center> <button name="button">Run Upgrade</button> </center>
	    </tr>
		<tr> 
			<h1> </h1>
		</tr>
		    <tr>
	   		<center>Please keep the volumeknob pressed for 15 sec.</BR> </center>
     	    
                         <center>Once the light in the speaker dims, you can release it</BR> </center> 
            
                 <center>As soon as the update finishes, the unit restarts</center>
		</tr>		

	  </table>
	</p>
    </form>
